version: 0.0
os: linux
files:
  - source: /twopointoh
    destination: /var/www/itemizer
permissions:
  - object: /var/www
    pattern: "itemizer"
    owner: apache
    group: apache
    mode: 766
    type:
      - directory
  - object: /var/www/itemizer
    pattern: "*"
    owner: apache
    group: apache
    mode: 766
    type:
      - directory
  - object: /var/www/itemizer/css
    pattern: "*"
    owner: apache
    group: apache
    mode: 664
    type:
      - file
  - object: /var/www/itemizer/dashboard
    pattern: "*"
    owner: apache
    group: apache
    mode: 664
    type:
      - file
  - object: /var/www/itemizer/details
    pattern: "*"
    owner: apache
    group: apache
    mode: 664
    type:
      - file
  - object: /var/www/itemizer/img
    pattern: "*"
    owner: apache
    group: apache
    mode: 664
    type:
      - file
  - object: /var/www/itemizer/js
    pattern: "*"
    owner: apache
    group: apache
    mode: 664
    type:
      - file
  - object: /var/www/itemizer/js
    pattern: "*"
    owner: apache
    group: apache
    mode: 766
    type:
      - directory
  - object: /var/www/itemizer/js/modules
    pattern: "*"
    owner: apache
    group: apache
    mode: 664
    type:
      - file
